
import { Seller, Product } from '../types.ts';

export const mockSellers: Seller[] = [
  {
    id: 's1',
    fullName: 'PK MART Official Store',
    email: 'admin@pkmart.pk',
    phoneNumber: '03079490721',
    shopId: 's1',
    joinedAt: '2024-01-01',
    payoutInfo: {
      method: 'JazzCash',
      accountNumber: '03079490721',
      accountTitle: 'PK MART ADMIN'
    }
  }
];

// List of 500 items provided by user
const productData = [
  ["Basic T-Shirt", 20], ["Premium T-Shirt", 28], ["Graphic T-Shirt", 30], ["Polo Shirt", 32], ["Long Sleeve T-Shirt", 26],
  ["Half Sleeve Shirt", 29], ["Formal Shirt", 40], ["Office Shirt", 38], ["Linen Shirt", 42], ["Denim Shirt", 45],
  ["Hoodie", 45], ["Oversized Hoodie", 52], ["Zipper Hoodie", 48], ["Fashion Hoodie", 55], ["Sweatshirt", 40],
  ["Crewneck Sweatshirt", 44], ["Jacket", 65], ["Denim Jacket", 85], ["Leather Jacket", 120], ["Bomber Jacket", 95],
  ["Windbreaker", 70], ["Rain Jacket", 75], ["Waterproof Jacket", 88], ["Puffer Jacket", 105], ["Down Jacket", 115],
  ["Winter Coat", 135], ["Trench Coat", 120], ["Blazer", 90], ["Formal Blazer", 95], ["Sports Jacket", 80],
  ["Tracksuit", 75], ["Team Tracksuit", 85], ["Joggers", 40], ["Sweatpants", 38], ["Cargo Pants", 55],
  ["Khaki Pants", 45], ["Jeans", 60], ["Ripped Jeans", 65], ["Slim Fit Jeans", 58], ["Straight Jeans", 55],
  ["Shorts", 30], ["Denim Shorts", 35], ["Sport Shorts", 28], ["Cycling Shorts", 34], ["Sleep Shorts", 22],
  ["Leggings", 30], ["Winter Leggings", 42], ["Yoga Pants", 38], ["Jeggings", 34], ["Lounge Wear", 60],
  ["Nightwear Set", 45], ["Pajama Set", 48], ["Bathrobe", 55], ["Jumpsuit", 65], ["Romper", 50],
  ["Skirt", 35], ["Long Skirt", 40], ["Mini Skirt", 32], ["Dress", 70], ["Casual Dress", 60],
  ["Party Dress", 85], ["Evening Gown", 120], ["Sports Bra", 32], ["Workout Top", 28], ["Compression Shirt", 36],
  ["Base Layer", 40], ["Thermal Wear", 45], ["Vest", 35], ["Cardigan", 50], ["Sweater", 48],
  ["Kids T-Shirt", 18], ["Kids Hoodie", 30], ["Kids Jacket", 55], ["Baby Romper", 22], ["Baby Suit", 35],
  ["School Uniform", 45], ["College Hoodie", 50], ["Lab Coat", 42], ["Chef Coat", 48], ["Nurse Scrubs", 55],
  ["Scrub Pants", 40], ["Construction Vest", 30], ["Safety Jacket", 45], ["Rain Poncho", 25], ["Cycling Jersey", 45],
  ["Football Jersey", 60], ["Cricket Jersey", 58], ["Basketball Jersey", 55], ["Baseball Jersey", 52], ["Custom Jersey", 70],
  ["Training Vest", 28], ["Gym Tank Top", 24], ["Muscle Shirt", 26], ["Beach Wear Set", 48], ["Swim Shorts", 35],
  ["Swimsuit", 55], ["Bikini", 60], ["Rash Guard", 42], ["Surf Suit", 75], ["Thermal Socks", 20],
  ["Wool Sweater", 55], ["Cashmere Sweater", 120], ["Long Coat", 140], ["Faux Fur Coat", 130], ["Parka Jacket", 125],
  ["Sherpa Jacket", 110], ["Softshell Jacket", 95], ["Fleece Jacket", 85], ["Quilted Jacket", 100], ["Track Pants", 45],
  ["Running Tights", 38], ["Compression Pants", 42], ["Dance Wear", 50], ["Yoga Set", 65], ["Pilates Outfit", 60],
  ["Martial Arts Uniform", 90], ["Karate Gi", 95], ["Taekwondo Suit", 92], ["Judo Uniform", 98], ["Boxing Shorts", 35],
  ["Wrestling Singlet", 55], ["Cycling Bib Shorts", 75], ["Ski Pants", 110], ["Ski Jacket", 150], ["Snow Suit", 165],
  ["Thermal Shirt", 48], ["Thermal Pants", 50], ["Hunting Jacket", 120], ["Tactical Pants", 85], ["Military Jacket", 140],
  ["Safari Shirt", 55], ["Fishing Vest", 65], ["Rain Suit", 90], ["Work Overalls", 75], ["Mechanic Suit", 80],
  ["Coveralls", 78], ["Apron", 25], ["Kitchen Apron", 28], ["Barber Cape", 30], ["Salon Gown", 35],
  ["Spa Robe", 65], ["Hospital Gown", 40], ["Patient Wear", 38], ["Maternity Dress", 60], ["Nursing Top", 45],
  ["Maternity Leggings", 50], ["Ethnic Kurta", 55], ["Kurta Pajama", 70], ["Sherwani", 180], ["Waistcoat", 65],
  ["Nehru Jacket", 85], ["Abaya", 120], ["Hijab", 25], ["Kaftan", 75], ["Thobe", 90],
  ["Ihram", 45], ["Dance Costume", 95], ["Stage Costume", 110], ["Halloween Costume", 80], ["Santa Suit", 85],
  ["Mascot Costume", 250], ["Animal Costume", 180], ["Cosplay Outfit", 150], ["Anime Costume", 140], ["Superhero Suit", 160],
  ["Racing Suit", 220], ["Firefighter Suit", 260], ["Pilot Uniform", 180], ["Airline Crew Uniform", 170], ["Security Uniform", 120],
  ["Police Uniform", 150], ["Army Combat Suit", 200], ["Camouflage Pants", 75], ["Camouflage Shirt", 65], ["Tactical Vest", 95],
  ["Bulletproof Vest", 320], ["Rainproof Pants", 60], ["Windproof Jacket", 85], ["Heat Resistant Suit", 280], ["Cold Storage Suit", 240],
  ["Medical PPE Kit", 75], ["Disposable Gown", 20], ["Disposable Coverall", 30], ["Lab Scrubs Set", 65], ["X-Ray Lead Apron", 150],
  ["Welding Jacket", 110], ["Flame Resistant Pants", 95], ["Arc Flash Suit", 350], ["Chemical Resistant Suit", 300], ["Hazmat Suit", 420],
  ["Diving Suit", 220], ["Wetsuit", 180], ["Dry Suit", 350], ["Surf Shorts", 45], ["Beach Towel", 30],
  ["Bath Towel", 28], ["Hand Towel", 15], ["Bath Mat", 22], ["Robe Towel Set", 65], ["Premium Lounge Set", 95],
  ["Sneakers", 120], ["Running Shoes", 100], ["Training Shoes", 95], ["Trail Shoes", 110], ["Hiking Boots", 140],
  ["Leather Boots", 135], ["Chelsea Boots", 125], ["Formal Shoes", 115], ["Loafers", 90], ["Sandals", 30],
  ["Slippers", 22], ["Flip Flops", 20], ["Sports Sandals", 38], ["Football Cleats", 130], ["Cricket Shoes", 120],
  ["Basketball Shoes", 150], ["Tennis Shoes", 125], ["Golf Shoes", 160], ["Boxing Shoes", 95], ["Wrestling Shoes", 90],
  ["Cycling Shoes", 140], ["Skate Shoes", 110], ["Work Boots", 150], ["Safety Shoes", 130], ["Steel Toe Boots", 160],
  ["Rain Boots", 55], ["Snow Boots", 145], ["Ski Boots", 220], ["Military Boots", 180], ["Tactical Boots", 165],
  ["Kids Sneakers", 60], ["Kids Sandals", 30], ["Baby Shoes", 25], ["School Shoes", 55], ["Orthopedic Shoes", 140],
  ["Diabetic Shoes", 135], ["Slip Resistant Shoes", 120], ["Chef Shoes", 110], ["Nurse Shoes", 105], ["Hospital Clogs", 90],
  ["Backpack", 55], ["Laptop Bag", 60], ["Travel Backpack", 75], ["Hiking Backpack", 120], ["School Bag", 45],
  ["College Bag", 55], ["Office Bag", 70], ["Leather Backpack", 130], ["Crossbody Bag", 45], ["Sling Bag", 40],
  ["Messenger Bag", 65], ["Tote Bag", 50], ["Handbag", 75], ["Clutch Bag", 45], ["Shoulder Bag", 70],
  ["Gym Bag", 55], ["Duffle Bag", 65], ["Sports Kit Bag", 70], ["Travel Duffel", 85], ["Wheeled Duffel", 120],
  ["Suitcase Small", 140], ["Suitcase Medium", 180], ["Suitcase Large", 220], ["Cabin Luggage", 160], ["Hard Shell Luggage", 240],
  ["Garment Bag", 90], ["Shoe Bag", 25], ["Laundry Bag", 20], ["Camera Bag", 85], ["Drone Bag", 120],
  ["Wallet", 25], ["Leather Wallet", 45], ["Card Holder", 18], ["Money Clip", 22], ["Coin Pouch", 15],
  ["Belt", 28], ["Leather Belt", 40], ["Tactical Belt", 55], ["Fashion Belt", 35], ["Suspenders", 30],
  ["Watch", 65], ["Smart Watch", 180], ["Sports Watch", 120], ["Luxury Watch", 350], ["Fitness Band", 85],
  ["Sunglasses", 40], ["Sports Sunglasses", 55], ["Polarized Sunglasses", 70], ["Reading Glasses", 30], ["Blue Light Glasses", 35],
  ["Cap", 25], ["Snapback Cap", 28], ["Baseball Cap", 26], ["Beanie", 20], ["Bucket Hat", 26],
  ["Fedora Hat", 38], ["Sun Hat", 35], ["Winter Hat", 30], ["Helmet", 95], ["Motorcycle Helmet", 180],
  ["Cycling Helmet", 120], ["Ski Helmet", 160], ["Safety Helmet", 45], ["Face Mask", 10], ["Sports Mask", 18],
  ["Balaclava", 25], ["Neck Gaiter", 20], ["Scarf", 22], ["Wool Scarf", 35], ["Shawl", 30],
  ["Gloves", 20], ["Winter Gloves", 26], ["Touchscreen Gloves", 30], ["Boxing Gloves", 85], ["Gym Gloves", 25],
  ["Cycling Gloves", 35], ["Ski Gloves", 65], ["Safety Gloves", 30], ["Socks Pack", 18], ["Ankle Socks", 12],
  ["Crew Socks", 15], ["Compression Socks", 22], ["Thermal Socks", 20], ["Arm Sleeves", 18], ["Knee Support", 30],
  ["Elbow Support", 28], ["Wrist Support", 22], ["Ankle Support", 25], ["Back Support Belt", 45], ["Posture Corrector", 35],
  ["Sports Towel", 20], ["Gym Towel", 18], ["Cooling Towel", 22], ["Headband", 15], ["Sweatband", 12],
  ["Bandana", 10], ["Hair Cap", 8], ["Jewelry Set", 75], ["Necklace", 45], ["Bracelet", 35],
  ["Ring", 40], ["Earrings", 30], ["Cufflinks", 35], ["Tie", 20], ["Bow Tie", 22],
  ["Pocket Square", 15], ["Handkerchief", 10], ["Keychain", 12], ["Phone Pouch", 20], ["Waist Bag", 35],
  ["Running Belt", 30], ["Travel Organizer", 40], ["Passport Holder", 25], ["ID Card Holder", 15], ["Luggage Tag", 10],
  ["Shoe Cleaner Kit", 20], ["Shoe Polish Kit", 25], ["Sneaker Cleaner", 22], ["Shoe Deodorizer", 15], ["Clothing Steamer", 85],
  ["Iron Press", 75], ["Fabric Shaver", 35], ["Lint Roller", 10], ["Wardrobe Organizer", 45], ["Hanger Set", 25],
  ["Storage Box", 40], ["Vacuum Storage Bag", 30], ["Shoe Rack", 85], ["Coat Rack", 90], ["Laundry Basket", 35],
  ["Drying Rack", 75], ["Travel Pillow", 30], ["Eye Mask", 15], ["Ear Plugs", 10], ["Travel Blanket", 45],
  ["Picnic Blanket", 55], ["Sleeping Bag", 120], ["Camping Mat", 65], ["Tent", 220], ["Camping Chair", 75],
  ["Camping Table", 95], ["Thermal Flask", 35], ["Water Bottle", 25], ["Sports Bottle", 30], ["Hydration Pack", 85],
  ["Lunch Box", 20], ["Food Container Set", 35], ["Cooler Bag", 55], ["Ice Pack", 10], ["First Aid Kit", 45],
  ["Emergency Kit", 75], ["Survival Kit", 120], ["Torch Light", 25], ["Head Lamp", 35], ["Power Bank", 45],
  ["Travel Adapter", 30], ["Luggage Scale", 20], ["GPS Tracker", 85], ["Smart Tag", 35], ["Anti Theft Lock", 25],
  ["Cable Lock", 20], ["RFID Wallet", 55], ["Money Belt", 30], ["Travel Safe", 120], ["Fireproof Bag", 75],
  ["Waterproof Pouch", 25], ["Dry Bag", 45], ["Rain Cover", 20], ["Umbrella", 30], ["Windproof Umbrella", 45],
  ["Compact Umbrella", 25], ["Golf Umbrella", 55], ["Travel Kit", 40], ["Grooming Kit", 35], ["Shaving Kit", 30],
  ["Toiletry Bag", 25], ["Makeup Bag", 35], ["Cosmetic Organizer", 45], ["Jewelry Organizer", 40], ["Shoe Organizer", 50],
  ["Closet Organizer", 85], ["Drawer Organizer", 30], ["Storage Basket", 35], ["Foldable Box", 25], ["Laundry Organizer", 40],
  ["Travel Cube Set", 45], ["Packing Cubes", 40], ["Compression Bags", 35], ["Suit Cover", 30], ["Garment Steamer", 95],
  ["Mini Iron", 55], ["Sewing Kit", 15], ["Repair Kit", 25], ["Shoe Repair Kit", 30], ["Button Set", 10],
  ["Fabric Tape", 8], ["Tailor Measuring Tape", 5], ["Clothes Brush", 12], ["Fabric Spray", 15], ["Odor Remover", 18],
  ["Anti Wrinkle Spray", 20], ["Shoe Tree", 25], ["Boot Shaper", 30], ["Hat Box", 45], ["Watch Box", 65],
  ["Sunglasses Case", 15], ["Phone Case", 20], ["Tablet Sleeve", 35], ["Laptop Sleeve", 45], ["Camera Strap", 30],
  ["Camera Cleaning Kit", 25], ["Lens Pouch", 20], ["Tripod Bag", 40], ["Drone Case", 95], ["Action Cam Mount", 30],
  ["Sports Armband", 18], ["Running Light", 25], ["Reflective Vest", 30], ["Safety Whistle", 5], ["Emergency Blanket", 15],
  ["Rain Poncho", 20], ["Travel Raincoat", 35], ["Folding Cap", 22], ["UV Protection Sleeves", 18], ["Cooling Cap", 28],
  ["Thermal Cap", 25], ["Sweat Proof Headband", 15], ["Gym Sack", 20], ["Drawstring Bag", 18], ["Reusable Tote", 15],
  ["Eco Shopping Bag", 12], ["Beach Bag", 45], ["Straw Hat", 30], ["Beach Slippers", 25], ["Pool Slides", 28],
  ["Water Shoes", 40], ["Snorkeling Fins", 85], ["Snorkel Mask", 75], ["Diving Goggles", 55], ["Swim Cap", 15],
  ["Ear Plugs Swim", 10], ["Towel Poncho", 45], ["Beach Chair", 95], ["Sun Shade Tent", 140], ["Picnic Basket", 85],
  ["Hammock", 65], ["Outdoor Mat", 45], ["Folding Stool", 35], ["Camping Stove", 120], ["Gas Canister", 25],
  ["Cookware Set", 95], ["Camping Kettle", 40], ["Portable Grill", 150], ["BBQ Tools Set", 75], ["Fire Starter", 20],
  ["Survival Knife", 85], ["Multi Tool", 65], ["Compass", 25], ["Emergency Radio", 95], ["Solar Charger", 111]
];

export const mockProducts: Product[] = productData.map((p, i) => ({
  id: `prd-grid-${i}`,
  sellerId: 's1',
  sellerName: 'PK MART Official Store',
  name: p[0] as string,
  description: `Authentic Pakistani ${p[0]} manufactured with premium materials. Export quality guaranteed by PK MART.`,
  price: (p[1] as number) * 280, // Convert USD to PKR (estimated rate)
  views: Math.floor(Math.random() * 90) / 10 + 1, // Random views from 1.0 to 9.9 million
  currency: 'PKR',
  category: i < 70 ? 'Apparel' : i < 150 ? 'Specialty' : i < 240 ? 'Footwear' : 'Accessories',
  imageUrl: `https://images.unsplash.com/photo-${1500000000000 + i}?w=800&auto=format`, 
  stock: 500,
  published: true,
  createdAt: new Date().toISOString()
}));

export const mockOrders: any[] = [];
